# Generated by Django 4.0.6 on 2022-07-29 03:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211130_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_steps',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
