# Generated by Django 4.0.4 on 2022-06-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings_time_unit',
            field=models.CharField(max_length=65),
        ),
    ]
