# Generated by Django 4.0.4 on 2022-06-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_alter_recipe_preparation_time_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_time',
            new_name='servings',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_time_unit',
            new_name='servings_unit',
        ),
    ]
